### ISSUE TITLE
Response [Text] from Gemini split into several parts

### ISSUE THREAD

**Issue by jeromemassot** [heiko-hotz/gemini-multimodal-live-dev-guide#2]
Hi,

I have run several of the notebooks and codes in this repository (thanks a lot) and have the following question: **Why is the response text received from Gemini so fragmented?**

Example:

with the chapter03 code I obtained the following output text (I have changed the system instruction to prepend 'I hear you, Jerome' to each model's response) :

```
Connected to Gemini

You: Hello! Are you there?

Gemini: I

Gemini: hear you, Jerome. Yes, I am here. How can I help you

Gemini: today?
```

Why is the **response server content split into three chunks** ['I', 'hear you, Jerome. Yes, I am here. How can I help you', 'today?'] ?

Remark: same behavior without customized system instruction.

Thanks for the help

Jerome

**Comment by jeromemassot** [comment]
I have checked and as expected each 'Gemini: ...' corresponds to a distinct server response. So why so many server responses for generating a single sentence?

**Comment by heiko-hotz** [comment]
Hi Jerome, the Live API is, by design, a streaming API. That means it will always stream responses at a given interval, that is why you will see text responses being chunked up. For complete text responses I would suggest the REST API instead. 

Let me know if that answers your question.

**Comment by jeromemassot** [comment]
Thanks for your comment. Yes, it confirms my thoughts about the Streaming API behavior. I was unsure if the high frequency of "chunks" was a feature or an issue. The queue management makes the audio output transparent. For the text output, as you mentioned, the standard non-streaming API seems more appropriate if I do not want to badly post-process the text chunks :)

**Comment by jeromemassot** [comment]
The provided information is consistent. The issue is closed. Thanks
